### ISSUE TITLE
Add tests for two identical cases

### ISSUE THREAD

**Issue by Jackbaude** [containers/netavark-dhcp-proxy-deprecated#50]
Per discussion of [this PR](https://github.com/containers/netavark-dhcp-proxy/pull/43#discussion_r1044890896), add test cases for two identical leases that are added. Adding an identical lease should not panic and discard the identical lease.

**Comment by Jackbaude** [comment]
Ive looked into the implementation of `HashMap::insert()`, it says:

> If the map did not have this key present, [None](https://doc.rust-lang.org/std/option/enum.Option.html#variant.None) is returned.
> If the map did have this key present, the value is updated, and the old value is returned. The key is not updated, though; this matters for types that can be == without being identical. See the [module-level documentation](https://doc.rust-lang.org/std/collections/index.html#insert-and-complex-keys) for more.

I believe that using the `insert` method takes care of the logic here, and that testing is not needed. PTAL @baude

**Comment by baude** [comment]
no, the test is still valid
